name: build
on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: images/build -d

  linters:
    name: lint and vendor check / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-22.04]  # TODO: pass linters on 'macos-10.15' and 'windows-2019'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Make check
        run: |
          make lint
          make verify-boilerplate
          hack/verify-go-modules.sh
          hack/verify-docs.sh
      - name: Test
        run: make test-crictl

  releases:
    name: releases / on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]  # TODO: make releases on 'linux-ppc64le' 'windows-2019'
                                         # Ref: https://github.com/uraimo/run-on-arch-action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Make release
        run: make release
